config:
  title:                  Playa
  google_analytics:       UA-5216615-13
  google_webmaster_tools: i8NjOC8rJvuvTJANxL3ZU5lemfbFkovx0ZqSCYwg430
  twitter:                '@moonwavelabs'
  links:
    author:
      site: https://www.diegocaponera.com
      email: hello@diegocaponera.com
    github: https://github.com/moonwave99/playa
    waffel: https://moonwave99.github.io/waffel
    tachyons: https://tachyons.io
    discogs: https://www.discogs.com
    stack:
      electron: https://www.electronjs.org
      react: https://reactjs.org/
      redux: https://redux.js.org/
      pouchdb: https://pouchdb.com/

structure:
  home:
    template: home
    url:      /
  about:
    template: about
    url:      /about
  blog:
    collection: blog
    pages:
      index:
        template: blog/index
        url:      /devblog
        paginate: 5
        priority: 0.5
        filter:
          published: true
        sort:
          field: date
          order: desc
      single:
        template: blog/single
        url:      /devblog/:date/:slug
        priority: 0.8
        filter:
          published: true
  404:
    template: '404'
    url:      '404'
    sitemap:  false
