config:
  title:                  Playa
  google_analytics:       UA-XXXXXXX-Y
  google_webmaster_tools: xyz
  twitter:                '@moonwavelabs'
  links:
    author: https://www.diegocaponera.com
    github: https://github.com/moonwave99/playa
    download: https://github.com/moonwave99/playa/releases/download/v0.2.3/Playa-darwin-x64_v0.2.3.zip
    waffel: http://moonwave99.github.io/waffel
    tachyons: http://tachyons.io
    discogs: https://www.discogs.com
    stack:
      electron: https://www.electronjs.org
      react: https://reactjs.org/
      redux: https://redux.js.org/
      pouchdb: https://pouchdb.com/

structure:
  home:
    template: home
    url:      /
  about:
    template: about
    url:      /about
  blog:
    collection: blog
    pages:
      index:
        template: blog/index
        url:      /devblog
        paginate: 5
        priority: 0.5
        filter:
          published: true
        sort:
          field: date
          order: desc
      single:
        template: blog/single
        url:      /devblog/:date/:slug
        priority: 0.8
        filter:
          published: true
  404:
    template: '404'
    url:      '404'
    sitemap:  false
